---
title: "Read Data On the Web"
author: "Shaolei Ma"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load the necessary libraries..

```{r setup}
library(rvest)
library(httr)
```

Import the NSDUH data

```{r}
nsduh_url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html =
  read_html(nsduh_url)
```

```{r}
marj_use_df = 
  nsduh_html |> 
  html_table() |> 
  first() |> # take the first element
  slice(-1) # remove the first row
```

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
title_vec = 
  swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()

gross_rev_vec = 
  swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".runtime") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

## APIs

 * make sure the program is reproducible.
 
 * make sure the data is up to date.

Get water data from NYC.

```{r}
nyc_water_df =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> # get the result of the api
  content("parsed") # get the content ("parsed" unnecessary in this case)
```

BRFSS Data.

```{r}
brfss_df = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content()
```

Try it now!

```{r}
poke_df =
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```

